const panels = [
  {
    title: "Andaló",
    address: "Av. Alberto Andaló, 4300 - Vl. Redentora",
    reference: "Av. Alberto Andaló em frente ao Mc’Donalds",
    backgroundImg: "/img/andalo.jpeg",
    download: "/download/andalo.pdf",
    map: "-20.8228454,-49.3851396",
  },
  {
    title: "Iguatemi",
    address: "Av. Pres. Juscelino K. de oliveira, 4200",
    reference: "Rotatória de acesso de frente ao Shopping Iguatemi",
    backgroundImg: "/img/iguatemi.jpeg",
    download: "/download/iguatemi.pdf",
    map: "-20.8648625,-49.4134475",
  },
  {
    title: "Redentora",
    address: "Av. Pres. Juscelino K. de oliveira, 4200",
    reference: "Av. Faria Lima com R. Bernardino de Campos",
    backgroundImg: "/img/redentora.jpeg",
    download: "/download/redentora.pdf",
    map: "-20.8228313,-49.3923151",
  },
  {
    title: "Região Norte",
    address: "Av. Cenobelino de Barros Serra",
    reference:
      "Av. Cenobelino de Barros (acesso região Norte / Shopping Norte)",
    backgroundImg: "/img/norte.jpeg",
    download: "/download/regiaonorte.pdf",
    map: "-20.7920818,-49.3876510",
  },
  {
    title: "Telus",
    address: "Av. Arthur Nonatto",
    reference:
      "Av. Arthur Nonatto com Marg. Washington Luiz (sentido Rio Preto Shopping)",
    backgroundImg: "/img/telus.jpeg",
    download: "/download/telus.pdf",
    map: "-20.8238764,-49.3946292",
  },
  {
    title: "Murchid Homsi",
    address: "Av. Murchid Homsi",
    reference: "Av. Murchid Homsi",
    backgroundImg: "/img/homsi.png",
    download: "/download/homsi.pdf",
    map: "-20.8178805,-49.3662282",
  },
  {
    title: "Philadelpho",
    address: "Av. Philadelpho Manoel Gouveia Neto",
    reference: "Av. Philadelpho (Mc Donald’s)",
    backgroundImg: "/img/philadelpho.jpeg",
    download: "/download/philadelpho.pdf",
    map: "-20.7997609,-49.3771760",
  },
  {
    title: "Renê",
    address: "Av. Bady Bassit",
    reference: "Av. Bady Bassit | sentido centro",
    backgroundImg: "/img/rene.jpeg",
    download: "/download/rene.pdf",
    map: "-20.8216340,-49.3990212",
  },
  {
    title: "Anúbis",
    address: "Av. Alberto Andaló,",
    reference: "Av. Alberto Andaló sentido Centro",
    backgroundImg: "/img/anubis.jpeg",
    download: "/download/anubis.pdf",
    map: "-20.8189133,-49.3822126",
  },
];
export default panels;
